config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :orders do
    resource :checkout, :controller => 'checkout' do
      member do
        get :liqpay_result
        get :liqpay_status
      end
    end
  end

  post '/liqpay_status/:payment_method_id' => 'liqpay_status#update', :as => :liqpay_status_update

end

app/models/spree/payment_method/liqpay.rb
module Spree
  class PaymentMethod::Liqpay < PaymentMethod
    preference :server, :string, default: 'https://www.liqpay.com'
    preference :public_key, :string, default: ''
    preference :private_key, :string, default: ''
    preference :order_description, :string, default: -> {Spree::Store.current.name}
    preference :test_mode, :boolean, default: true

    def provider_class
      ActiveMerchant::Billing::Liqpay
    end

    def provider
      @provider ||= provider_class.new preferred_public_key, preferred_private_key
    end

    def source_required?
      false
    end

    def checkout_url
      "#{preferred_server}/api/checkout"
    end

    def cnb_form_fields order, result_url, server_url
      provider.cnb_form_fields amount: order.total,
                               currency: order.currency,
                               description: preferred_order_description,
                               order_id: order.id,
                               result_url: result_url,
                               server_url: server_url,
                               sandbox: preferred_test_mode ? 1 : 0
    end

    def check_signature data, signature
      provider.check_signature data, signature
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree
  CheckoutController.class_eval do
    def liqpay_result
      update if has_completed_payments?
    end

    def liqpay_status
      render json: {completed: has_completed_payments?}
    end

    private

    def has_completed_payments?
      @order.payments.completed.any?
    end
  end
end

app/controllers/spree/liqpay_status_controller.rb
module Spree
  class LiqpayStatusController < ApplicationController

    skip_before_filter :verify_authenticity_token

    # callbacks from Liqpay server
    def update
      @payment_method = PaymentMethod.find params[:payment_method_id]
      data = JSON.parse Base64.strict_decode64 params[:data]
      render text: "Bad signature\n", status: 401 and return unless @payment_method.check_signature params[:data], params[:signature]
      @order = Order.find data['order_id']

      raise ArgumentError unless @order.payments.completed.empty? &&
        data['currency'] == @order.currency &&
        BigDecimal(data['amount']) == @order.total &&
        data['type'] == 'buy' &&
        (data['status'] == 'success' || (@payment_method.preferred_test_mode && data['status'] == 'sandbox'))

      payment = @order.payments.create amount: @order.total, payment_method: @payment_method
      payment.complete!

      render text: "Thank you.\n"
    end
  end
end

app/views/spree/checkout/liqpay_result.html.erb
<script>
    $(function() {
        setInterval(function(){
            $.getJSON('<%= liqpay_status_order_checkout_url(@order, format: :json) %>', function(data) {
                if (data.completed) location.reload();})}, 500)});
</script>
<div id="liqpay_spinner">
  <!-- Here is the best place for some exciting animation -->
</div>

app/views/spree/checkout/payment/_liqpay.html.erb
<script>
  $(function() {
      var checkout_form = $('#checkout_form_payment');
      var checkout_form_action = checkout_form.prop('action');
      var radio = $('#order_payments_attributes__payment_method_id_<%= payment_method.id %>')
      var change_submit_url = function() {
          checkout_form.prop('action', radio.prop('checked') ? '<%= payment_method.checkout_url %>' : checkout_form_action);
      };
      $('input[type=radio][name="order[payments_attributes][][payment_method_id]"]', checkout_form).change(change_submit_url);
      change_submit_url();
  })
</script>
<% payment_method.cnb_form_fields(@order, liqpay_result_order_checkout_url(@order),
                                  liqpay_status_update_url(payment_method.id)).each do |name, value| %>
  <%= hidden_field_tag name, value %>
<% end %>